services:
  picture-api-pg:
    image: bitnami/postgresql
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=nodeapi
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    depends_on:
      - picture-api-pg
    container_name: picture-api
    environment:
      - DATABASE_URL=postgresql://docker:docker@picture-api-pg:5432/picture-api?schema=public
    expose:
      - "3333"
    ports:
      - "3333:3333"
    command: npm run start:dev